server:
  port: 8081
  max-http-header-size: 20480
  
spring:
  application:
   name: service-provider

eureka:
  instance:
    prefer-ip-address: true  
    instance-id: ${spring.cloud.client.ip-address}:${server.port} 
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka/
